services:
  chartdb:
    image: ghcr.io/chartdb/chartdb:latest
    container_name: orgatick-chartdb

    ports:
      - "6060:80" 

    env_file:
      - ../../.env
 
    environment:
      DISABLE_ANALYTICS: "true"

    restart: unless-stopped