import {
  ANALYTICS_PERMISSIONS,
  CERTIFICATE_PERMISSIONS,
  CHECKIN_PERMISSIONS,
  COMMUNICATION_PERMISSIONS,
  COUPON_PERMISSIONS,
  EVENT_PERMISSIONS,
  ORGANIZATION_PERMISSIONS,
  PAYMENT_PERMISSIONS,
  PERMISSION_DEFINITIONS,
  type PermissionKey,
  REFERRAL_PERMISSIONS,
  REGISTRATION_PERMISSIONS,
  SESSION_PERMISSIONS,
  TICKET_PERMISSIONS,
} from "../permissions";

export const DEFAULT_ROLE_KEYS = {
  OWNER: "owner",
  ADMIN: "admin",
  EVENT_MANAGER: "event_manager",
  VOLUNTEER: "volunteer",
} as const;

export type DefaultRoleKey = (typeof DEFAULT_ROLE_KEYS)[keyof typeof DEFAULT_ROLE_KEYS];

export interface DefaultRoleDefinition {
  key: DefaultRoleKey;
  name: string;
  description: string;
  permissions: readonly PermissionKey[];
}

export const DEFAULT_ROLES: readonly DefaultRoleDefinition[] = [
  {
    key: DEFAULT_ROLE_KEYS.OWNER,
    name: "Owner",
    description: "Organization owner with full administrative, financial, and operational access",
    permissions: PERMISSION_DEFINITIONS.map((def) => def.key as PermissionKey),
  },
  {
    key: DEFAULT_ROLE_KEYS.ADMIN,
    name: "Admin",
    description: "Administrator with broad operational and management access across the organization and events",
    permissions: [
      // Organization operations (excluding organization:delete, organization:payout:manage, organization:member:remove)
      ORGANIZATION_PERMISSIONS.VIEW,
      ORGANIZATION_PERMISSIONS.UPDATE,
      ORGANIZATION_PERMISSIONS.MEMBER_VIEW,
      ORGANIZATION_PERMISSIONS.MEMBER_INVITE,
      ORGANIZATION_PERMISSIONS.MEMBER_UPDATE,
      ORGANIZATION_PERMISSIONS.DOCUMENT_VIEW,
      ORGANIZATION_PERMISSIONS.DOCUMENT_UPLOAD,
      ORGANIZATION_PERMISSIONS.DOCUMENT_DELETE,
      ORGANIZATION_PERMISSIONS.PAYOUT_VIEW,
      ORGANIZATION_PERMISSIONS.SETTING_VIEW,
      ORGANIZATION_PERMISSIONS.SETTING_UPDATE,

      // Event management
      EVENT_PERMISSIONS.CREATE,
      EVENT_PERMISSIONS.VIEW,
      EVENT_PERMISSIONS.UPDATE,
      EVENT_PERMISSIONS.DELETE,
      EVENT_PERMISSIONS.PUBLISH,
      EVENT_PERMISSIONS.UNPUBLISH,
      EVENT_PERMISSIONS.CANCEL,
      EVENT_PERMISSIONS.ARCHIVE,

      // Ticket management
      TICKET_PERMISSIONS.CREATE,
      TICKET_PERMISSIONS.VIEW,
      TICKET_PERMISSIONS.UPDATE,
      TICKET_PERMISSIONS.DELETE,
      TICKET_PERMISSIONS.PAUSE,
      TICKET_PERMISSIONS.MANAGE_INVENTORY,

      // Registration management
      REGISTRATION_PERMISSIONS.VIEW,
      REGISTRATION_PERMISSIONS.CREATE,
      REGISTRATION_PERMISSIONS.UPDATE,
      REGISTRATION_PERMISSIONS.CANCEL,
      REGISTRATION_PERMISSIONS.REFUND,
      REGISTRATION_PERMISSIONS.TRANSFER,
      REGISTRATION_PERMISSIONS.EXPORT,
      REGISTRATION_PERMISSIONS.RESEND_CONFIRMATION,

      // Session management
      SESSION_PERMISSIONS.CREATE,
      SESSION_PERMISSIONS.VIEW,
      SESSION_PERMISSIONS.UPDATE,
      SESSION_PERMISSIONS.DELETE,
      SESSION_PERMISSIONS.SPEAKER_MANAGE,

      // Check-in management
      CHECKIN_PERMISSIONS.VIEW,
      CHECKIN_PERMISSIONS.SCAN,
      CHECKIN_PERMISSIONS.MANUAL,
      CHECKIN_PERMISSIONS.OVERRIDE,
      CHECKIN_PERMISSIONS.EXPORT,

      // Certificate management
      CERTIFICATE_PERMISSIONS.CREATE,
      CERTIFICATE_PERMISSIONS.VIEW,
      CERTIFICATE_PERMISSIONS.UPDATE,
      CERTIFICATE_PERMISSIONS.DELETE,
      CERTIFICATE_PERMISSIONS.GENERATE,
      CERTIFICATE_PERMISSIONS.REVOKE,
      CERTIFICATE_PERMISSIONS.EXPORT,

      // Coupon management
      COUPON_PERMISSIONS.CREATE,
      COUPON_PERMISSIONS.VIEW,
      COUPON_PERMISSIONS.UPDATE,
      COUPON_PERMISSIONS.DELETE,

      // Referral management
      REFERRAL_PERMISSIONS.CREATE,
      REFERRAL_PERMISSIONS.VIEW,
      REFERRAL_PERMISSIONS.UPDATE,
      REFERRAL_PERMISSIONS.DELETE,
      REFERRAL_PERMISSIONS.PAYOUT,

      // Analytics
      ANALYTICS_PERMISSIONS.ORGANIZATION_VIEW,
      ANALYTICS_PERMISSIONS.ORGANIZATION_EXPORT,
      ANALYTICS_PERMISSIONS.EVENT_VIEW,
      ANALYTICS_PERMISSIONS.EVENT_EXPORT,

      // Communication
      COMMUNICATION_PERMISSIONS.ORGANIZATION_TEMPLATE_MANAGE,
      COMMUNICATION_PERMISSIONS.EVENT_VIEW,
      COMMUNICATION_PERMISSIONS.EVENT_SEND,
      COMMUNICATION_PERMISSIONS.EVENT_SCHEDULE,

      // Payment
      PAYMENT_PERMISSIONS.ORGANIZATION_VIEW,
      PAYMENT_PERMISSIONS.EVENT_VIEW,
      PAYMENT_PERMISSIONS.EVENT_REFUND_APPROVE,
    ],
  },
  {
    key: DEFAULT_ROLE_KEYS.EVENT_MANAGER,
    name: "Event Manager",
    description:
      "Event manager focused on event planning, ticketing, agenda, attendee registration, and event operations",
    permissions: [
      // Event management
      EVENT_PERMISSIONS.CREATE,
      EVENT_PERMISSIONS.VIEW,
      EVENT_PERMISSIONS.UPDATE,
      EVENT_PERMISSIONS.DELETE,
      EVENT_PERMISSIONS.PUBLISH,
      EVENT_PERMISSIONS.UNPUBLISH,
      EVENT_PERMISSIONS.CANCEL,
      EVENT_PERMISSIONS.ARCHIVE,

      // Ticket management
      TICKET_PERMISSIONS.CREATE,
      TICKET_PERMISSIONS.VIEW,
      TICKET_PERMISSIONS.UPDATE,
      TICKET_PERMISSIONS.DELETE,
      TICKET_PERMISSIONS.PAUSE,
      TICKET_PERMISSIONS.MANAGE_INVENTORY,

      // Registration management
      REGISTRATION_PERMISSIONS.VIEW,
      REGISTRATION_PERMISSIONS.CREATE,
      REGISTRATION_PERMISSIONS.UPDATE,
      REGISTRATION_PERMISSIONS.CANCEL,
      REGISTRATION_PERMISSIONS.REFUND,
      REGISTRATION_PERMISSIONS.TRANSFER,
      REGISTRATION_PERMISSIONS.EXPORT,
      REGISTRATION_PERMISSIONS.RESEND_CONFIRMATION,

      // Session management
      SESSION_PERMISSIONS.CREATE,
      SESSION_PERMISSIONS.VIEW,
      SESSION_PERMISSIONS.UPDATE,
      SESSION_PERMISSIONS.DELETE,
      SESSION_PERMISSIONS.SPEAKER_MANAGE,

      // Check-in management
      CHECKIN_PERMISSIONS.VIEW,
      CHECKIN_PERMISSIONS.SCAN,
      CHECKIN_PERMISSIONS.MANUAL,
      CHECKIN_PERMISSIONS.OVERRIDE,
      CHECKIN_PERMISSIONS.EXPORT,

      // Certificate management
      CERTIFICATE_PERMISSIONS.CREATE,
      CERTIFICATE_PERMISSIONS.VIEW,
      CERTIFICATE_PERMISSIONS.UPDATE,
      CERTIFICATE_PERMISSIONS.DELETE,
      CERTIFICATE_PERMISSIONS.GENERATE,
      CERTIFICATE_PERMISSIONS.REVOKE,
      CERTIFICATE_PERMISSIONS.EXPORT,

      // Coupon management
      COUPON_PERMISSIONS.CREATE,
      COUPON_PERMISSIONS.VIEW,
      COUPON_PERMISSIONS.UPDATE,
      COUPON_PERMISSIONS.DELETE,

      // Referral management
      REFERRAL_PERMISSIONS.CREATE,
      REFERRAL_PERMISSIONS.VIEW,
      REFERRAL_PERMISSIONS.UPDATE,
      REFERRAL_PERMISSIONS.DELETE,
      REFERRAL_PERMISSIONS.PAYOUT,

      // Event Analytics
      ANALYTICS_PERMISSIONS.EVENT_VIEW,
      ANALYTICS_PERMISSIONS.EVENT_EXPORT,

      // Event Communication
      COMMUNICATION_PERMISSIONS.EVENT_VIEW,
      COMMUNICATION_PERMISSIONS.EVENT_SEND,
      COMMUNICATION_PERMISSIONS.EVENT_SCHEDULE,

      // Event Payment
      PAYMENT_PERMISSIONS.EVENT_VIEW,
    ],
  },
  {
    key: DEFAULT_ROLE_KEYS.VOLUNTEER,
    name: "Volunteer",
    description: "Staff and volunteers assisting with on-site check-in, attendance scanning, and event schedules",
    permissions: [
      EVENT_PERMISSIONS.VIEW,
      SESSION_PERMISSIONS.VIEW,
      REGISTRATION_PERMISSIONS.VIEW,
      CHECKIN_PERMISSIONS.VIEW,
      CHECKIN_PERMISSIONS.SCAN,
      CHECKIN_PERMISSIONS.MANUAL,
    ],
  },
] as const;
