import type { PermissionDefinition } from "../types/permission.types";

export const NEWSLETTER_PERMISSIONS = {
  VIEW: "newsletter:view",
  SUBSCRIBER_VIEW: "newsletter:subscriber:view",
  SUBSCRIBER_MANAGE: "newsletter:subscriber:manage",
  TEMPLATE_VIEW: "newsletter:template:view",
  TEMPLATE_MANAGE: "newsletter:template:manage",
  LIST_MANAGE: "newsletter:list:manage",
  CAMPAIGN_VIEW: "newsletter:campaign:view",
  CAMPAIGN_CREATE: "newsletter:campaign:create",
  CAMPAIGN_UPDATE: "newsletter:campaign:update",
  CAMPAIGN_SEND: "newsletter:campaign:send",
  CAMPAIGN_CANCEL: "newsletter:campaign:cancel",
} as const;

export type NewsletterPermission = (typeof NEWSLETTER_PERMISSIONS)[keyof typeof NEWSLETTER_PERMISSIONS];

export const NEWSLETTER_PERMISSION_DEFINITIONS: readonly PermissionDefinition[] = [
  {
    key: NEWSLETTER_PERMISSIONS.VIEW,
    name: "View Newsletter",
    description: "Allows opening the newsletter overview and dashboard counters",
    resource: "newsletter",
    action: "view",
    scope: "platform",
    category: "newsletter",
  },
  {
    key: NEWSLETTER_PERMISSIONS.SUBSCRIBER_VIEW,
    name: "View Newsletter Subscribers",
    description: "Allows browsing subscriber lists, statuses and engagement statistics",
    resource: "newsletter",
    action: "subscriber_view",
    scope: "platform",
    category: "newsletter",
  },
  {
    key: NEWSLETTER_PERMISSIONS.SUBSCRIBER_MANAGE,
    name: "Manage Newsletter Subscribers",
    description: "Allows subscribing, unsubscribing, blocking and exporting subscribers",
    resource: "newsletter",
    action: "subscriber_manage",
    scope: "platform",
    category: "newsletter",
  },
  {
    key: NEWSLETTER_PERMISSIONS.TEMPLATE_VIEW,
    name: "View Newsletter Templates",
    description: "Allows browsing reusable newsletter templates",
    resource: "newsletter",
    action: "template_view",
    scope: "platform",
    category: "newsletter",
  },
  {
    key: NEWSLETTER_PERMISSIONS.TEMPLATE_MANAGE,
    name: "Manage Newsletter Templates",
    description: "Allows creating, editing, publishing and archiving newsletter templates",
    resource: "newsletter",
    action: "template_manage",
    scope: "platform",
    category: "newsletter",
  },
  {
    key: NEWSLETTER_PERMISSIONS.LIST_MANAGE,
    name: "Manage Mailing Lists",
    description: "Allows creating mailing lists, setting the default list and toggling list visibility",
    resource: "newsletter",
    action: "list_manage",
    scope: "platform",
    category: "newsletter",
  },
  {
    key: NEWSLETTER_PERMISSIONS.CAMPAIGN_VIEW,
    name: "View Newsletter Campaigns",
    description: "Allows browsing campaigns, per-recipient delivery records and engagement reports",
    resource: "newsletter",
    action: "campaign_view",
    scope: "platform",
    category: "newsletter",
  },
  {
    key: NEWSLETTER_PERMISSIONS.CAMPAIGN_CREATE,
    name: "Create Newsletter Campaigns",
    description: "Allows drafting new campaigns and saving them as templates",
    resource: "newsletter",
    action: "campaign_create",
    scope: "platform",
    category: "newsletter",
  },
  {
    key: NEWSLETTER_PERMISSIONS.CAMPAIGN_UPDATE,
    name: "Update Newsletter Campaigns",
    description: "Allows editing draft or scheduled campaigns, including scheduling them",
    resource: "newsletter",
    action: "campaign_update",
    scope: "platform",
    category: "newsletter",
  },
  {
    key: NEWSLETTER_PERMISSIONS.CAMPAIGN_SEND,
    name: "Send Newsletter Campaigns",
    description: "Allows sending, pausing, resuming and retrying campaign deliveries",
    resource: "newsletter",
    action: "campaign_send",
    scope: "platform",
    category: "newsletter",
  },
  {
    key: NEWSLETTER_PERMISSIONS.CAMPAIGN_CANCEL,
    name: "Cancel Newsletter Campaigns",
    description: "Allows cancelling a scheduled or in-flight campaign",
    resource: "newsletter",
    action: "campaign_cancel",
    scope: "platform",
    category: "newsletter",
  },
] as const;
