import type { PermissionDefinition } from "../types/permission.types";

export const ORGANIZATION_PERMISSIONS = {
  VIEW: "organization:view",
  UPDATE: "organization:update",
  DELETE: "organization:delete",
  MEMBER_VIEW: "organization:member:view",
  MEMBER_INVITE: "organization:member:invite",
  MEMBER_UPDATE: "organization:member:update",
  MEMBER_REMOVE: "organization:member:remove",
  DOCUMENT_VIEW: "organization:document:view",
  DOCUMENT_UPLOAD: "organization:document:upload",
  DOCUMENT_DELETE: "organization:document:delete",
  PAYOUT_VIEW: "organization:payout:view",
  PAYOUT_MANAGE: "organization:payout:manage",
  SETTING_VIEW: "organization:setting:view",
  SETTING_UPDATE: "organization:setting:update",
} as const;

export type OrganizationPermission = (typeof ORGANIZATION_PERMISSIONS)[keyof typeof ORGANIZATION_PERMISSIONS];

export const ORGANIZATION_PERMISSION_DEFINITIONS: readonly PermissionDefinition[] = [
  {
    key: ORGANIZATION_PERMISSIONS.VIEW,
    name: "View Organization",
    description: "Allows viewing organization details, profile, and overview",
    resource: "organization",
    action: "view",
    scope: "organization",
    category: "organization",
  },
  {
    key: ORGANIZATION_PERMISSIONS.UPDATE,
    name: "Update Organization",
    description: "Allows updating organization profile, branding, and details",
    resource: "organization",
    action: "update",
    scope: "organization",
    category: "organization",
  },
  {
    key: ORGANIZATION_PERMISSIONS.DELETE,
    name: "Delete Organization",
    description: "Allows deleting or requesting deletion of the organization",
    resource: "organization",
    action: "delete",
    scope: "organization",
    category: "organization",
  },
  {
    key: ORGANIZATION_PERMISSIONS.MEMBER_VIEW,
    name: "View Organization Members",
    description: "Allows viewing organization team members, roles, and invitation status",
    resource: "member",
    action: "view",
    scope: "organization",
    category: "organization_member",
  },
  {
    key: ORGANIZATION_PERMISSIONS.MEMBER_INVITE,
    name: "Invite Organization Members",
    description: "Allows sending invitations to new team members",
    resource: "member",
    action: "invite",
    scope: "organization",
    category: "organization_member",
  },
  {
    key: ORGANIZATION_PERMISSIONS.MEMBER_UPDATE,
    name: "Update Organization Members",
    description: "Allows changing roles, permissions, and status of organization members",
    resource: "member",
    action: "update",
    scope: "organization",
    category: "organization_member",
  },
  {
    key: ORGANIZATION_PERMISSIONS.MEMBER_REMOVE,
    name: "Remove Organization Members",
    description: "Allows removing members and revoking member invitations",
    resource: "member",
    action: "remove",
    scope: "organization",
    category: "organization_member",
  },
  {
    key: ORGANIZATION_PERMISSIONS.DOCUMENT_VIEW,
    name: "View Organization Documents",
    description: "Allows viewing verification and compliance documents of the organization",
    resource: "document",
    action: "view",
    scope: "organization",
    category: "organization_document",
  },
  {
    key: ORGANIZATION_PERMISSIONS.DOCUMENT_UPLOAD,
    name: "Upload Organization Documents",
    description: "Allows uploading business verification and identity documents",
    resource: "document",
    action: "upload",
    scope: "organization",
    category: "organization_document",
  },
  {
    key: ORGANIZATION_PERMISSIONS.DOCUMENT_DELETE,
    name: "Delete Organization Documents",
    description: "Allows deleting uploaded organization verification documents",
    resource: "document",
    action: "delete",
    scope: "organization",
    category: "organization_document",
  },
  {
    key: ORGANIZATION_PERMISSIONS.PAYOUT_VIEW,
    name: "View Payout Accounts",
    description: "Allows viewing organization payout bank accounts and settlement info",
    resource: "payout",
    action: "view",
    scope: "organization",
    category: "organization_setting",
  },
  {
    key: ORGANIZATION_PERMISSIONS.PAYOUT_MANAGE,
    name: "Manage Payout Accounts",
    description: "Allows adding, updating, and verifying organization bank accounts for payouts",
    resource: "payout",
    action: "manage",
    scope: "organization",
    category: "organization_setting",
  },
  {
    key: ORGANIZATION_PERMISSIONS.SETTING_VIEW,
    name: "View Organization Settings",
    description: "Allows viewing organization-level preferences and configurations",
    resource: "setting",
    action: "view",
    scope: "organization",
    category: "organization_setting",
  },
  {
    key: ORGANIZATION_PERMISSIONS.SETTING_UPDATE,
    name: "Update Organization Settings",
    description: "Allows modifying organization-level preferences, branding, and defaults",
    resource: "setting",
    action: "update",
    scope: "organization",
    category: "organization_setting",
  },
] as const;
